version: "3.9"
services:
  web: 
    # build: . # ne updejta??
    image: "flask-tutorial:latest"
    ports:
      - "5000:5000"
  db:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongo_data:
      
  # redis:
  #   image: "redis:alpine"