version: "3.9"
services:
  web: 
    # build: . # ne updejta??
    image: "flask-tutorial:latest"
    ports:
      - "5000:5000"
  db:
    image: "mongo:4.2"
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
      
  # redis:
  #   image: "redis:alpine"